<?php

namespace App\Http\Middleware;

use App\Models\User;
use Closure;
use Illuminate\Auth\Middleware\AuthenticateWithBasicAuth;

class Authenticate extends AuthenticateWithBasicAuth
{
    public function handle($request, Closure $next, $guard = null, $field = null)
    {
        if (User::count() === 0) {
            return $next($request);
        }
        return parent::handle($request, $next, $guard, $field); // TODO: Change the autogenerated stub
    }

}
